wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.5
    cli_version: 0.15.7
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1722433805.370816
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 13
      - 23
      4: 3.8.5
      5: 0.15.7
      8:
      - 5
